### PR TITLE
Feature emscripten

### PR DESCRIPTION
**Pull request by tin-nl**
Finally the promised patch for emscripten support. Please note that I have no idea how to integrate this _properly_ as I'm lacking the cmake mastery to do so (I don't - and won't - use cmake).

Also forgive the ugly cpu hack, but emscripten likes his functions to have just one declaration when it comes to function signatures.

How to build:
1. install emscripten and the sdl2 port, aktivate emscripten latest (preferably in windows wsl)
2. mkdir -p build
	cd build
	emmake cmake -DEMSCRIPTEN=true -DCMAKE_SYSTEM_NAME=Linux ..
(the DCMAKE_SYSTEM_NAME is just to force the cpugen to be build for the host and not the target system, there is surely a better solution that involves changing ./configure)
3. emmake make -j10 hatari

This should be enough of a pointer to build a "proper" emscripten integration.

### CODE REVIEW

**Comment by huth** [comment]
Thank you very much for providing the patches! ... I unfortunately currently lack the spare time to have a closer look at this right now, but I'll try to take care of it as soon as possible. I also did some experiments with emscripten in the past with projects that are using cmake, so I'm confident that I should be able to figure out a usable solution for that, too.

**Comment by huth** [comment]
I finally found some spare minutes, and indeed also got it working here. However, the third patch if very ugly, indeed. But after doing some experiments, it rather seems to me that the "Cycle Exact" mode is simply not working, and you can also get a usable build by using this way more simpler patch instead:

```
diff a/src/configuration.c b/src/configuration.c
--- a/src/configuration.c
+++ b/src/configuration.c
@@ -766,7 +766,11 @@ void Configuration_SetDefault(void)
        ConfigureParams.System.bCompatibleFPU = true; /* JIT */
        ConfigureParams.System.bSoftFloatFPU = false;
        ConfigureParams.System.bMMU = false;
+#ifdef EMSCRIPTEN
+       ConfigureParams.System.bCycleExactCpu = false;
+#else
        ConfigureParams.System.bCycleExactCpu = true;
+#endif
        ConfigureParams.System.VideoTimingMode = VIDEO_TIMING_MODE_WS3;
        ConfigureParams.System.bCompatibleCpu = true;
        ConfigureParams.System.bBlitter = false;
```

**Comment by tin-nl** [comment]
Are you _sure_ that cycle exact is not working? I have a few fullscreen in the atariaviary, the beg to differ :)

Also: w/o cycle exact mode, the emscripten web emulation is getting useless (at least to my use case).

Or a I getting wrong, what "cycle exact" means in this case? I'm referring to the cycle exact CPU emulation, as in: disabling it would not perform the CPU emulations the hardware does?

**Comment by huth** [comment]
Thanks again - patches have been merged now (with some minor tweaking):

- https://git.tuxfamily.org/hatari/hatari.git/commit/?id=bd9a8bd2ec84dddce369c04d1ad89c3a8a7f8bb2
- https://git.tuxfamily.org/hatari/hatari.git/commit/?id=dbac8617a7bacab72ebf4fae4201ecabc787ced7

**Comment by tin-nl** [comment]
> Are you _sure_ that cycle exact is not working? I have a few fullscreens in the atariaviary that beg to differ :)
> 
> Also: w/o cycle exact mode, the emscripten web emulation is getting useless (at least to my use case).
> 
> Or am I getting wrong what "cycle exact" means in this case? I'm referring to the cycle exact CPU emulation, as in: disabling it would not perform the CPU emulation using the same timing as the hardware does?

Any answers to this, tho?

**Comment by huth** [comment]
"Cycle Exact" in UAE CPU speech means: Cycles are emulated on a sub-instruction granularity. Without that mode, you still get instruction cycle emulation that is very close to the hardware, but only at instruction boundaries. For most demos and games, that's still good enough, but there might some few where this sub-instruction granularity might be necessary (I can't think of a concrete example right now, though ... maybe @npomarede knows one).

**Comment by huth** [comment]
The thing is that in your "ugly" final patch, you've replaced  "cpuop_func_ce" with  "cpuop_func" ... thus if I get that right, this basically disables the "cycle exact"  mode (the "ce" suffix means "cycle exact").

**Comment by tin-nl** [comment]
> "Cycle Exact" in UAE CPU speech means: Cycles are emulated on a sub-instruction granularity. Without that mode, you still get instruction cycle emulation that is very close to the hardware, but only at instruction boundaries. For most demos and games, that's still good enough, but there might some few where this sub-instruction granularity might be necessary (I can't think of a concrete example right now, though ... maybe @npomarede knows one).

That'd be interesting to know yes. 

Thanks for clearing that up, I was kinda fearing that that change would have an impact on fullscreen et al, which would've been a shame.


> The thing is that in your "ugly" final patch, you've replaced "cpuop_func_ce" with "cpuop_func" ... thus if I get that right, this basically disables the "cycle exact" mode (the "ce" suffix means "cycle exact").

That's entirely possible, I just had the "darn, this should compile" hat on and did not notice any degradation with any sync code or demo code protections (well, "yet" :) ), so I deemed this being "ok".

**Comment by npomarede** [comment]
Le 02/10/2022 à 15:56, tin-nl a écrit :
>     "Cycle Exact" in UAE CPU speech means: Cycles are emulated on a
>     sub-instruction granularity. Without that mode, you still get
>     instruction cycle emulation that is very close to the hardware, but
>     only at instruction boundaries. For most demos and games, that's
>     still good enough, but there might some few where this
>     sub-instruction granularity might be necessary (I can't think of a
>     concrete example right now, though ... maybe @npomarede
>     <https://github.com/npomarede> knows one).
> 
> That'd be interesting to know yes.
> 
> Thanks for clearing that up, I was kinda fearing that that change would 
> have an impact on fullscreen et al, which would've been a shame.
> 
>     The thing is that in your "ugly" final patch, you've replaced
>     "cpuop_func_ce" with "cpuop_func" ... thus if I get that right, this
>     basically disables the "cycle exact" mode (the "ce" suffix means
>     "cycle exact").
> 
> That's entirely possible, I just had the "darn, this should compile" hat 
> on and did not notice any degradation with any sync code or demo code 
> protections (well, "yet" :) ), so I deemed this being "ok".

Hi

the difference between "prefetch mode" and "cycle accurate" is sometimes 
thin.
This is because when I started contributing, there was only the UAE cpu 
core, which supported normal and prefetch mode, but not cycle accurate, 
which was required for fullscreen demos for example.

So I added some special cases to the "prefetch mode" to handle all/most 
of what was needed to emulate cycle accurate code.

Then WinUAE cpu was added, which features a "real" cycle exact mode. 
That is it really emulates memory cycle accesses, accurate exception at 
the cycle level (iack sequence for example), correct stack content in 
the case of bus/address error, etc.

I would say that 95% of demos are working in prefetch mode, most games too.
Then some games protection might require very specific stack emulation, 
which will need cycle accurate mode.

Regarding demos, "Closure" by Sync for example won't work in prefetch 
mode : it requires some really precise emulation of STOP, HBL jitter 
(using E clock).

Nicolas

**Comment by tin-nl** [comment]
Thanks for the information - "cycle exact" had a far bigger gap regarding emulation a few versions before when being disabled.

That said tho: http://absencehq.de/atariaviary/?id=181484 works fine with my patch; can you do a quick test @huth if it does work with yours? I'm asking because it only breaks when I disable "cycle exact" in the config menu of my patched version, which _might_ hint that the patch currently in Hatari isn't equivalent to mine regarding emulation accuracy.

**Comment by npomarede** [comment]
I can have a look at this ; do you have some logs of the errors reported by emscripten when patch #2 is not applied ?

**Comment by tin-nl** [comment]
@npomarede Since it's a runtime error (let's call it "runtime linking" or sth like that) - not really. It's basically sth along the lines of:

`Uncaught RuntimeError: null function or function signature mismatch
    at m68k_run_1_ce (newcpu.c:5426:15)
    at main (newcpu.c:7645:3)
    at ret.<computed> (hatari.js:22009:35)
    at Object.doRewind (hatari.js:22074:16)
    at hatari.js:22099:47
    at callUserCallback (hatari.js:18066:9)
    at hatari.js:18079:9`

which boils down to the function actually called not fullfilling the function pointer's declaration (here: the function does "return" instead of "return <int32>", which screws up the call stack frame in wasm/ems). Again, not sure what the cpu core is trying to do there, but in my (humble) opinion the runtime is fully in it's right to complain. And yes, there _are_ ways to auto-cast functions in emscripten, but that has _severe_ performance implications. Apart from finding this (and other caveats), getting a solution that actually results in a ok-ish performance was the main time sink here.

**Comment by huth** [comment]
As far as I understood the problem, it's because the CPU core uses two functions types for emulating instructions, one for cycle-exact emulation (where cycles are handled differently and thus the functions can be declared as "void"), and one for the other modes where cycles are returned via a return value. From newcpu.h:

```
typedef uae_u32 REGPARAM3 cpuop_func (uae_u32) REGPARAM;
typedef void REGPARAM3 cpuop_func_ce (uae_u32) REGPARAM;
```

Now the problem is that the CPU core code tries to stuff both function types into the same array, see newcpu.c:

```
cpuop_func *cpufunctbl[65536];
```

In gencpu.c, you can see that the _ce functions are casted into the non-ce mode like this:

```
        fprintf(headerfile, "extern %s op_%04x_%d%s_ff;\n",
                (using_ce || using_ce020) ? "(cpuop_func*)" : ""
```

... which works OK with "traditional" C compilers, but apparently Emscripten does not like this at all. And I guess this would also cause problems when compiling with a compiler that has control-flow integrity checks enabled (see e.g. https://clang.llvm.org/docs/ControlFlowIntegrity.html).

To fix the issue, I think there are basically two options:

1) Drop the difference in the function types - that's what @tin-nl did. This drops of course the optimization that the CE functions do not need a return value, so it could have a small performance impact on the normal (non-emscripten) builds.

2) Try to disentangle the cpufunctbl array in newcpu.c into two arrays and use one array for *_ce functions and one array for the non-ce functions. Not sure whether that's easily possible, though ...

Maybe we should ask @tonioni (from https://github.com/tonioni/WinUAE ) for his thoughts?

**Comment by npomarede** [comment]
That's what I saw too and came exactly to the same conclusion as you ):
 - make all functions have return int, even if its value is useless in CE mode
 - change cpufunctbl used in build_cpufunctbl to use CE mode yes/no and have 2 opcode arrays. This would require some changes in newcpu.c, but not that much, mainly adding a pointer cpufunctbl_current for example that would point to the CE or non_CE array of opcodes.

2nd solution would be less hacky and even more correct from a pointer/prototype point of view. I will send a mail to Toni to see if he would be interested in changing this. If not, 1st solution would be the way to go, as even it's more a hack it has much less impact when merging code with WinUAE (we have very difference with WinUAE's gencpu.c, so it would not impact merging that much, compared to newcpu.c where we already have a lot of differences)

**Comment by tonioni** [comment]
Oops, yet another "temporary" hack that was never properly fixed. I'll fix it in next few days.

**Comment by npomarede** [comment]
Thanks to @tonioni , WinUAE was updated yesterday to separate the 2 types of opcode functions.
I pushed the changes to Hatari devel tree + a few other changes required for our opcodes' interception (VDI, Line A, ...) and confirm it worked in STF/TT/Falcon with or without CE mode
@tin-nl can you check this  completely remove the need for your patch #2 ?

**Comment by huth** [comment]
FWIW, cycle exact mode is working fine for me now with Emscripten, too! Thanks, @tonioni !

**Comment by huth** [comment]
@npomarede, seems like two tests are failing in the CI now, in 68040 "compatible" mode:

https://cirrus-ci.com/task/6615128157192192?logs=main#L536

Maybe there are still some spots missing where the wrong cpufunctbl* is used?

**Comment by npomarede** [comment]
I will have a look at the 2 failing tests

**Comment by tin-nl** [comment]
@npomarede current build looks good regarding clock cycle emulation; I get working fullscreens and 2 cycle accuracy - so it's looking good on my end. Thanks alot @tonioni, @huth and @npomarede for your great support to get this humble patch integrated!

**Comment by npomarede** [comment]
regarding hatari's tests failing in 68040 prefetch mode : @tonioni  in "m68k_run_3p" you now use cpufunctbl_noret ; isn't that a mistake ? run_3p doesn't use the return value because it forces 1 cycle for each opcode, but cpufunctbl_noret should be used only in CE mode from what I see in gencpu.c . So run_"p should still use cpufunctbl ?

**Comment by npomarede** [comment]
@tonioni  : or not .. it seems 68040 in prefetch mode (not CE mode) use cpuemu_24.cpp anyway. So run_3p shoud use the _noret version, and I need to update other parts in Hatari that assumed that run_3p was not in CE mode.
Is that really wanted that 68040 prefetch uses same cpu table as 68040 CE ? Or am I misreading the code ?

**Comment by tonioni** [comment]
It is technically correct. 68040+ don't have any kind of real cycle-exact modes. Not much point to generate yet another cpu core.

**Comment by npomarede** [comment]
OK, Hatari has been fixed and 68040 with prefetch mode works correctly now using the _noret functions. All tests are passing in the CI.

**Comment by huth** [comment]
> Finally the promised patch for emscripten support. Please note that I have no idea how to integrate this _properly_ as I'm lacking the cmake mastery to do so (I don't - and won't - use cmake).

FYI, as I found out recently, a "proper" integration with CMake is easy, since there is a wrapper for cmake, too, which takes care of selecting a proper toolchain file. Simply run "emcmake" instead of "emmake" when configuring the build with cmake, and it sets up things like CMAKE_SYSTEM_NAME automatically.

**Pull request closed without merging**
