### PR TITLE
Cleanup of palettized-PNG, NEO and XIMG support

### PR DESCRIPTION
**Pull request by bbbradsmith**
Cleanup intended to consolidate: #30, #31, #33, #34

Implementing suggestions made by Eero Tamminen on the mailing list:
* Static arrays converted to function-local stack arrays.
* Using be_swap16 instead of custom StoreNEOU16.
* Consolidate shared code between SaveNEO/SaveXIMG.
* Document the command line --screnshot-format which was added.
* Document the revised screen dialog.

Additionally:
* Add XIMG option to the GUI.
* Add "ximg" command line option.

Including from #33 and #34:
* NEO format should support any GenConv format that matches one of the 3 standard ST resolutions.
* XIMG screenshot format.
* ConvertNextLine passes line memory stride information from GenConv (rather than duplicating/assuming it).
* Filename field in NEO indicates HATARI and BPP.

### CODE REVIEW

**Comment by bbbradsmith** [comment]
The CI failure looks spurious, the only change was the HTML documentation, but the logged failure was an instruction test on cygwin only?

**Comment by huth** [comment]
> The CI failure looks spurious, the only change was the HTML documentation, but the logged failure was an instruction test on cygwin only?

I think I've seen the "command-fifo" test failing on some few occasion in the past weeks, but failed to reproduce it so far ... seems to be a bit flaky ... you can certainly ignore it for this PR here for now.

**Review by npomarede — COMMENTED** [review]
Seems good for me, I merged everything into Hatari

**Comment by npomarede** [comment]
Closing this PR as everything was merged into Hatari

**Pull request closed without merging**
